name: testPipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

- name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt
          pip install pytest

      # Debugging output
      - name: Check current directory and list files after pipeline
        run: |
          pwd
          ls -la

      - name: Set execute permissions and run tests
        run: |
          chmod +x project/tests.sh
          ./project/tests.sh
